### ISSUE TITLE
error when .env isnt present

### ISSUE THREAD

**Issue by carnal0wnage** [carnal0wnage/weirdAAL#57]
if you just DL the repo, install deps, and just doing weirdAAL.py -h  you'll get something similar to below

```
(weirdAAL-python) lookupfailed-2:weirdAAL-gcp CG$ python3 weirdAAL.py 
Traceback (most recent call last):
  File "weirdAAL.py", line 27, in <module>
    exec("from %s import *" % module)
  File "<string>", line 1, in <module>
  File "/Users/CG/Documents/pentest/weirdAAL/modules/aws/cloudtrail.py", line 4, in <module>
    from libs.cloudtrail import *
  File "/Users/CG/Documents/pentest/weirdAAL/libs/cloudtrail.py", line 22, in <module>
    AWS_ACCESS_KEY_ID = credentials.access_key
AttributeError: 'NoneType' object has no attribute 'access_key'
```
this is because nothing can be loaded because the .env load is failing. just do the

`cp env.sample .env`

and you should be able to get to further with the start process

**Comment by carnal0wnage** [comment]
closing this just wanted to capture it in case other people run into it
