### ISSUE TITLE
dependency deprecation - must use python3.9

### ISSUE THREAD

**Issue by tmechen** [carnal0wnage/weirdAAL#79]
```
Traceback (most recent call last):
  File "/Users/xy/weirdAAL/weirdAAL.py", line 18, in <module>
    from tabulate import tabulate
  File "/Users/xy/weirdAAL/weirdAAL/lib/python3.10/site-packages/tabulate.py", line 7, in <module>
    from collections import namedtuple, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```
-----

The Iterable abstract class was removed from collections in Python 3.10.

**Comment by imflikk** [comment]
I know this was a while ago, but for anyone else who finds this issue in the future you should be able to fix it by updating the version of tabulate used in requirements.txt.  It was mentioned and fixed in one of the [issues](https://github.com/astanin/python-tabulate/issues/278) for that library.

Change `tabulate==0.8.2` to `tabulate==0.9.0`
